### ISSUE TITLE
[FIX] pylint-odoo fails to execute any setuptools command

### ISSUE THREAD

**Issue by LuisAlejandro** [Vauxoo/pylint-odoo#18]
This project uses several setup dependencies that are not listed in the `requirements.txt`, and because of that, any `python setup.py [COMMAND]` will complain about a dependency not being met.

For example:

```
$ python setup.py egg_info
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 264, in cfg_to_args
    wrap_commands(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 566, in wrap_commands
    cmdclass = ep.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/sphinx/setup_command.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python2.7/dist-packages/sphinx/application.py", line 31, in <module>
    from sphinx.roles import XRefRole
  File "/usr/local/lib/python2.7/dist-packages/sphinx/roles.py", line 21, in <module>
    from sphinx.util import ws_re
  File "/usr/local/lib/python2.7/dist-packages/sphinx/util/__init__.py", line 30, in <module>
    import jinja2
ImportError: No module named jinja2
error in setup command: Error parsing /home/huntingbears/Desarrollo/vauxoo/pylint-odoo/setup.cfg: ImportError: No module named jinja2
```

I suggest putting the setup requirements on `requirements.txt` so that this pylint plugin can be used without further hacking.

I will provide a PR for this later on.

Cheers.

**Comment by nhomar** [comment]
Agree.

make a PR please.
